steps:
  # Build the container image and push it with Kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --cache=true
    - --dockerfile=${_DOCKER_FILE}
    - --build-arg=SRC_DIR=${_APP}
    - --destination=eu.gcr.io/$PROJECT_ID/${_APP}:$COMMIT_SHA